---
title: "Initial EDA"
author: "Bruce Mallory"
date: "11/13/2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
pacman::p_load("maps","tmap", "tmaptools", "tigris",
               "tidyverse","drat", "magrittr", "sf", "dplyr", "readx1")
```

```{r cars}
data <- read.csv("dataverse_files/1976-2018-house2.csv")
data_1976 <- data %>% filter(year==1976)

data_1976 <- data_1976 %>%
   group_by(state_po,district) %>%
   mutate(max_st_year_vote = max(candidatevotes, na.rm=T))
          
          
seats_1976 <- data_1976 %>% group_by(state) %>% summarize(seats=length(unique(district)), .groups="drop")

group_cols <- c("state", "party")
votes_1976 <-data_1976 %>% group_by(across(all_of(group_cols))) %>%
  summarise(votes = sum(candidatevotes), .groups="drop") %>% 
  group_by(state) %>%
  mutate(state_total = sum(votes), party_percent=round(votes/state_total,2))

a_1976 <- full_join(votes_1976, seats_1976, by="state") %>% mutate(expected_seats=round(party_percent*seats))
```

## Including Plots

You can also embed plots, for example:

```{r pressure, echo=FALSE}
plot(pressure)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
